language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=/home/travis/build/Serhii-Yar/epam-py-project-yarovyy/department_app/

script:
  - coverage run -m unittest discover department_app/tests
  - coverage report

after_success:
  - coveralls